name: Sessylph
options:
  bundleIdPrefix: sh.saqoo
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.7.1"
    CURRENT_PROJECT_VERSION: "18"
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "15.0"

targets:
  Sessylph:
    type: application
    platform: macOS
    sources:
      - path: Sources/Sessylph
        excludes:
          - "**/.DS_Store"
          - "**/WebResources/**"
          - "**/TerminalBridge.swift"
          - "**/PTYProcess.swift"
      - path: ghostty/Vendor
        type: folder
        buildPhase: none
    dependencies:
      - target: SessylphNotifier
    postCompileScripts:
      - script: |
          set -e
          cp "${BUILT_PRODUCTS_DIR}/sessylph-notifier" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/Contents/MacOS/"
        name: "Embed sessylph-notifier"
        basedOnDependencyAnalysis: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: sh.saqoo.Sessylph
        PRODUCT_NAME: Sessylph
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: Sources/Sessylph/App/Info.plist
        CODE_SIGN_ENTITLEMENTS: Sessylph.entitlements
        DEVELOPMENT_TEAM: G5G54TCH8W
        CODE_SIGN_STYLE: Automatic
        SWIFT_INCLUDE_PATHS: "$(SRCROOT)/ghostty/Vendor"
        HEADER_SEARCH_PATHS: "$(SRCROOT)/ghostty/Vendor"
        LIBRARY_SEARCH_PATHS: "$(SRCROOT)/ghostty/Vendor"
        OTHER_LDFLAGS:
          - "-lghostty"
          - "-lz"
          - "-lc++"
          - "-framework Metal"
          - "-framework MetalKit"
          - "-framework IOSurface"
          - "-framework Carbon"
          - "-framework CoreGraphics"
          - "-framework CoreText"
          - "-framework QuartzCore"
    info:
      path: Sources/Sessylph/App/Info.plist
      properties:
        CFBundleName: Sessylph
        CFBundleDisplayName: Sessylph
        CFBundleIdentifier: sh.saqoo.Sessylph
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleExecutable: Sessylph
        LSMinimumSystemVersion: "15.0"
        NSHumanReadableCopyright: "Copyright © 2026 Saqoosha. All rights reserved."

  SessylphNotifier:
    type: tool
    platform: macOS
    sources:
      - path: Sources/SessylphNotifier
    settings:
      base:
        PRODUCT_NAME: sessylph-notifier
        SWIFT_VERSION: "6.0"
